from __future__ import annotations

from typing import Protocol

from deltadesk.schemas import CandidateTrade, Fill, OrderState, Snapshot


class Broker(Protocol):
    def place(self, trade: CandidateTrade, snap: Snapshot) -> list[Fill]: ...
    def mark(self, snap: Snapshot) -> None: ...
    def structure_premium(self, trade: CandidateTrade, snap: Snapshot) -> float | None: ...
    def close_structure(self, trade: CandidateTrade, snap: Snapshot, reason: str) -> list[Fill]: ...
    def flatten(self, snap: Snapshot) -> list[Fill]: ...
    def state(self, snap: Snapshot, mode: str) -> OrderState: ...
